app:
  environment: "development"
  log_level: "INFO"

audit:
  folder: "/Users/shravan/Documents/github/photo_organizer/test_output/run_logs"

storage:
  source_folder: "/Users/shravan/Documents/github/photo_organizer/test_images"
  destination_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/organized"

network_backup:
  enabled: true
  source_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/organized"
  destination_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/network_backup"
  trash_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/network_backup_trash"

cloud:
  enabled: true
  source_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/organized"
  destination_folder: "/Users/shravan/Pictures"

ftp:
  enabled: false
  use_env_credentials: true
  host: "${oc.env:FTP_HOST,''}"
  user: "${oc.env:FTP_USER,''}"
  password: "${oc.env:FTP_PASS,''}"
  source_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/organized"
  remote_folder: "${oc.env:FTP_REMOTE_ROOT,'/G/ftp_uploads'}"
  trash_folder: "/Users/shravan/Documents/github/photo_organizer/test_output/ftp_trash"
  port: "${oc.env:FTP_PORT,21}"
